nome = input("Digite o nome da aluna: ")
idade = int(input("Digite a idade da aluna: "))
altura = float(input("Digite a altura da aluna (use ponto como separador): "))
hobbies = input("Digite os hobbies da aluna, separando com vírgula: ")
hobbies1 = hobbies.split(",")
enderecoRua = input("Digite o nome da rua da aluna: ")
enderecoNum = int(input("Digite o número da rua da aluna: "))
enderecoCidade = input("Digite a cidade da aluna: ")
endereco = (enderecoRua, enderecoNum, enderecoCidade)
email = input("Digite o e-mail da aluna: ")
telefone = input("Digite o telefone da aluna: ")
contato = {"E-mail": email, "Telefone": telefone}

print("\nOlá, seguem informações sobre a aluna")
print("Nome:", nome)
print("Idade:", idade)
print("Altura:", altura)
print("Hobbies:", hobbies1)
print("Endereço:", endereco)
print("Contato:", contato)